# Generated by Django 5.1.3 on 2026-06-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Robot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("est_actif", models.BooleanField(default=False)),
                ("dernier_resultat", models.TextField(blank=True, null=True)),
                ("date_derniere_execution", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
