# Generated by Django 5.1.3 on 2026-06-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="robot",
            name="dernier_resultat",
        ),
        migrations.AddField(
            model_name="robot",
            name="score_viral_global",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
